site_name: CMScomLab
site_url: https://lab.cmscom.jp
repo_url: https://github.com/CMScomLab/cmscomlab.github.io
edit_uri: edit/main/docs/ # 編集ボタンのリンク先

copyright: Copyright &copy; 2026 <a href="https://www.cmscom.jp">CMScom</a>

theme:
  name: material
  language: ja
  features:
    - navigation.tabs        # 上部にグローバルナビゲーションを表示
    - navigation.tabs.sticky # ナビゲーションを固定
    - navigation.sections    # サイドバーのセクション化
    - navigation.indexes     # indexファイルをセクションリンクにする
    - navigation.top         # 「トップに戻る」ボタン
    - search.suggest         # 検索サジェスト
  logo: assets/images/cmscom_lab.svg
  favicon: assets/images/cmscom_lab.svg
  palette: 
    scheme: default          # default(白系) / slate(黒系)
    primary: indigo
    accent: indigo

extra:
  analytics:
    provider: google
    property: G-Z0GQJHB711 # Google Analytics 4 の測定 ID に書き換えてください

extra_css:
  - stylesheets/extra.css

# 拡張機能
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# プラグイン
plugins:
  - search
  - git-revision-date-localized
  - blog:
      blog_dir: blog
      post_url_format: "{date}/{slug}"
      archive: true
      categories: true

# ナビゲーション構造
nav:
  - Home: index.md
  - About: about.md
  - Projects: 
      - projects/index.md
      - 'net-vis': projects/net-vis.md
      - 'LSH Cascade PoC': projects/lsh-cascade-poc.md
  - Blog: blog/index.md
