site_name: CMScomLab
site_url: https://lab.cmscom.jp
repo_url: https://github.com/CMScomLab/cmscomlab.github.io
edit_uri: edit/main/docs/ # 編集ボタンのリンク先

theme:
  name: material
  language: ja
  features:
    - navigation.tabs        # 上部にグローバルナビゲーションを表示
    - navigation.top         # 「トップに戻る」ボタン
    - search.suggest         # 検索サジェスト
  palette: 
    scheme: default          # default(白系) / slate(黒系)

# 拡張機能
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# プラグイン
plugins:
  - search
  - git-revision-date-localized
  - blog:
      blog_dir: blog/posts
      post_url_format: "{date}/{slug}"
      archive: true
      categories: true

# ナビゲーション構造
nav:
  - Home: index.md
  - Projects: 
      - projects/index.md
      - 'Project A': projects/project-a.md
  - Blog: 
      - blog/index.md
